replicaCount: 1

backend:
  image:
    repository: 192.168.1.65/nhl_scanner/backend
    pullPolicy: IfNotPresent
    tag: "latest"

frontend:
  image:
    repository: 192.168.1.65/nhl_scanner/frontend
    pullPolicy: IfNotPresent
    tag: "latest"

service:
  backend:
    type: NodePort
    port: 8000
    nodePort: 30081
  frontend:
    type: NodePort
    port: 80
    nodePort: 30080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
